### ISSUE TITLE
Assertion error while trying to install pymc

### ISSUE THREAD

**Issue by jacaseyclyde** [pymc-devs/pymc2#153] opened 2017-03-02 23:23 UTC
Like the title says, I'm getting an Assertion Error when trying to install pymc (source of install doesnt seem to matter - I've tried pip, easy_install, and building form source). I meet all requirements, have gfortran and python-dev installed. Tried both python 2.7 and 3.6, and get the same error no matter what. Running on Ubuntu 16.04LTS, x64. Full text of the error is attached in file below, word of warning, it gives a very long error output. Any help is really appreciated, I'm really hoping it's something I've done wrong and not a bug specific to my system :/

[error.txt](https://github.com/pymc-devs/pymc/files/815363/error.txt)

**Comment by fonnesbeck** [comment] 2017-03-03 13:45
This looks like an f2py bug. Can you ensure that you have the latest release of Numpy installed?

**Comment by fonnesbeck** [comment] 2017-03-03 13:46
Actually, this looks like a duplicate of #151. There is a solution there that might get you up and running. It is indeed a Numpy issue.

**Closed as completed by fonnesbeck** 2017-03-03 13:46 UTC
